### ISSUE TITLE
randomInt and randomRange return numbers outside the specified range

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript-random#10]
At the moment, `randomRange` (and similarly, `randomInt`) is defined as
```purescript
randomRange min max = (((max - min) + min) *) <$> random
```
which is equivalent to
```purescript
randomRange min max = (max *) <$> random
```

Consequently, it returns numbers between `0.0` and `max` instead of between `min` and `max`.

**Comment by paf31** [comment]
Oh dear :P
